### ISSUE TITLE
Please clarify what this polyfill does?

### ISSUE THREAD

**Issue by nickchomey** [okikio/sharedworker#3]
I found this while trying to find a way to implement SharedWorker in Android for Chrome (the only remaining holdout for this mechanism). My question relates to what you wrote in your article:

> The major limitation with @okikio/sharedworker is that on browsers that don't natively support SharedWorker, you can't use @okikio/sharedworker as an across tab communication tool. But for everything else it's feature parity and spec. compliance should be great.

If this doesn't actually bring across-tab communication to browsers that don't support SharedWorker, what exactly does it do/what is the point of it? (Surely there's a point, but I'm just not seeing it. So, I hope you can explain it to me!).

**Comment by okikio** [comment]
It gives you the ability to create a shared worker and be relatively confident it won't break older browser and still works properly in modern browsers. I am however, working on an improvement to the project that will bring cross tab communication, in the mean while I recommend using `BroadcastChannel` for cross tab communication.
