### ISSUE TITLE
[BUG] v1.0.5 is not published in npm registry

### ISSUE THREAD

**Issue by marcalexiei** [okikio/sharedworker#6]
**Describe the bug**

v1.0.5 release is tagged: https://github.com/okikio/sharedworker/releases/tag/v1.0.5
however it is not available on npm registry: https://www.npmjs.com/package/@okikio/sharedworker?activeTab=versions

<img width="808" alt="image" src="https://github.com/okikio/sharedworker/assets/24919330/bc74a2b2-ee6a-41ac-9d08-c7b98846e466">

**To Reproduce**

```bash
npm i @okikio/sharedworker@1.0.5
```

**Expected behavior**

v1.0.5 should be available for download from npm registry

**Screenshots**

<img width="1019" alt="Screenshot 2023-12-13 at 08 41 56" src="https://github.com/okikio/sharedworker/assets/24919330/4a9cfce6-a33a-471b-b9bc-3201377ed754">

**Desktop:**
 - OS: MacOS
 - Browser: n/a
 - Version: 1.0.5

**Comment by okikio** [comment]
It has now been fixed sorry about that 😓 
![CleanShot 2023-12-13 at 17 05 28@2x](https://github.com/okikio/sharedworker/assets/17222836/d32f19b3-ef5d-41e4-8ed1-98b76f671c4a)
