### ISSUE TITLE
[BUG] Using <script type="module"> does not work since v1.0.5

### ISSUE THREAD

**Issue by H-L** [okikio/sharedworker#7]
**Describe the bug**
It seems that `window.sharedworker` is not defined by `@okikio/sharedworker/lib/index.js` anymore.
Console will return an error like : `TypeError: Right side of assignement cannot be destructured`.

I had the error on an "old" Safari 15.6 browser.

- Script is working correctly at `v1.0.4` but breaks at `v1.0.5` on this particular use case.
- It seems the way the script is compiled into `/lib` has changed, and does not have the necessary code to support older browser.

**To Reproduce**
Load the script using `<script type="module">` tags exactly as described in the README:

```html
<script src="https://unpkg.com/@okikio/sharedworker" type="module"></script>
<script type="module">
    // You can then use it like this
    const { SharedWorkerPolyfill: SharedWorker } = window.sharedworker; 
</script>
```
Console will return an error like : `TypeError: Right side of assignement cannot be destructured`.

**Expected behavior**
Loading the umd script as described in the docs works, and `window.sharedworker` is defined once `@okikio/sharedworker/lib/index.js` or `https://unpkg.com/@okikio/sharedworker` is loaded.

**Comment by H-L** [comment]
Only "Fix" I found comes from this `tsup` opened issue. It seems this bundler does not support umd yet, but there is a workaround using `esbuild` (used by `tsup`).

https://github.com/egoist/tsup/issues/924#issuecomment-1808276621

**Comment by okikio** [comment]
Thanks for bring the issue to my attention I'll draft a fix for it quickly

**Comment by okikio** [comment]
This should now be fixed, but please use `<script src="https://unpkg.com/@okikio/sharedworker"></script>` remove type module from the import, I'll have to update the docs sorry, for the inconvenience, here's a demo https://codepen.io/okikio/pen/qBvoygR?editors=1111

**Comment by H-L** [comment]
Thanks a lot for your quick reaction !

Just tried the `v1.0.7` on the same Safari 15.6 and the bug is fixed, using the `index.umd.js` version.

**Comment by okikio** [comment]
Awesome 👌
